### 1. Vérifier si un email est libre (Doit renvoyer true)
POST http://localhost:3000/rpc/is_email_available
Content-Type: application/json

{
  "p_email": "test@epfc.eu"
}

###

### 2. Créer le compte (Doit renvoyer un code 204 No Content)
POST http://localhost:3000/rpc/signup
Content-Type: application/json

{
  "p_email": "test@epfc.eu",
  "p_password": "Password123!",
  "p_full_name": "Client Test"
}

###

### 3. Vérifier si l'email est libre APRES inscription (Doit renvoyer false)
POST http://localhost:3000/rpc/is_email_available
Content-Type: application/json

{
  "p_email": "test@epfc.eu"
}

