@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiY2xpZW50Iiwic3ViIjoibWFtaWNoZWxAZXBmYy5ldSIsIm5hbWUiOiJNYXJjIiwidXNlcl9pZCI6NCwiZXhwIjoxNzgwMDY0Njg2fQ.FDk_ZBkGEiQ0Vc53w8USANQiQsV3_BWKkDWxcBiW_xo

POST http://localhost:3000/rpc/login
Content-Type: application/json

{
  "email": "mamichel@epfc.eu",
  "password": "Password1,"
}

###
GET http://localhost:3000/rpc/get_reservations
Authorization: Bearer {{token}}
Content-Type: application/json


