@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiY2xpZW50Iiwic3ViIjoibWFtaWNoZWxAZXBmYy5ldSIsIm5hbWUiOiJNYXJjIiwidXNlcl9pZCI6NCwiZXhwIjoxNzgwMzM1NDAwfQ.zbEYlFCxU07xzx8ctipyIZtx7rCQRD0WS-JIr-2MB0w

POST http://localhost:3000/rpc/login
Content-Type: application/json

{
  "email": "mamichel@epfc.eu",
  "password": "Password1,"
}

###
GET http://localhost:3000/rpc/get_reservations
Authorization: Bearer {{token}}
Content-Type: application/json


